package org.example.utils

object Constants {
    const val MEAL_CSV_FILE = "food.csv"
    const val INVALID_INPUT = "Invalid input"
    const val NO_MEALS_FOR_GYM_HELPER = "No meals match the desired protein and calories!!"
    const val NO_MEALS_FOR_POTATO = "No potato meals found."
    const val POTATO = "potato"
    const val SEARCH_QUERY_CAN_NOT_BE_EMPTY = "Search query cannot be empty or null"
    const val NO_MEALS_FOUND_MATCHING = "No meals found matching"
    const val UNEXPECTED_ERROR = "Unexpected error occurred"
    const val ERROR_FETCHING_MEALS = "Error fetching meals: "
    const val ERROR_WHILE_READING_FROM_FILE = "Error while reading from the file!!"
    const val INSUFFICIANT_DATA_IN_ROW = "Insufficient data in row while parsing!!"
    const val NO_POTATO_MEALS_FOUND = "😢 No potato meals found."
    const val I_LOVE_POTATO = "🥔 I 💛 Potato Meals:"
    const val MEAL = "🍽️ Meal #"
    const val I_LOVE_POTATO_HERE = "🥔 I 💛 Potato! Here are "
    const val MEAL_INCLUDE_POTATO = "meals that include potatoes:"
    const val ERROR = "❌ Error: "
    const val VIEW_MEAL_DETAILS = "Would you like to view the details of any of these meals? (Enter the number or 'n' to skip):"
    const val ENJOY_YOUR_MEAL = "Okay! Enjoy your potato meals! 🥔😋"
    const val INVALID_SELECTION = "Invalid selection. Please choose a valid number."
    const val DETAILS_MEAL = "🍽️ Details of"
    const val MINUTE_TO_PREPARE = "🕒 Minutes to prepare:"
    const val NUMBER_OF_STEP = "📖 Number of steps:"
    const val STEPS = "📝 Steps:"
    const val DESCRIPTION = "📃 Description:"
    const val NUTRITION = "🍎 Nutrition"
    const val NUMBER_OF_INGREDIENT = "🥣 Number of ingredients:"
    const val INGREDIENT = "🧂 Ingredients:"
    const val NA = "   N/A"
    const val SEE_MORE_MEALS = "Would you like to see more? (y/n)"
    const val YES = "y"
}